#  Does the inter-industry structure of the US economy in a given year allow it to meet external final demand? If so find a production vector that will meet it exactly.


In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load Data



In [2]:
# Load the USE matrix 
use_df = pd.read_csv('use_2017.csv',header=None)
print("USE Matrix dimensions:", use_df.shape)
print("USE Matrix head:\n", use_df.head())


USE Matrix dimensions: (168, 168)
USE Matrix head:
             0             1             2           3            4    \
0  SECTORNUMBER      1.000000      2.000000    3.000000     4.000000   
1             1  24060.879370   7719.985981    0.000082     0.000307   
2             2    820.856118  51235.612630    0.000064     0.000239   
3             3      0.000093      0.000053   71.587194   267.445890   
4             4      0.000579      0.000330  443.989218  1658.719727   

        5           6         7          8         9    ...         158  \
0  5.000000    6.000000  7.000000   8.000000  9.000000  ...  158.000000   
1  0.000785  143.016858  0.000623   3.186164  5.654032  ...   48.583056   
2  0.000611  679.569139  0.000486   0.000495  0.000878  ...   56.606132   
3  0.000019    0.642357  0.000015  11.891675  0.000027  ...   33.451662   
4  0.000118    3.983950  0.000094  73.753073  0.000170  ...   55.533392   

          159         160         161         162          163  

In [3]:
# Load the Make matrix
make_df = pd.read_csv('make_2017.csv', header=None)
print("MAKE Matrix dimensions:", make_df.shape)
print("MAKE Matrix head:\n", make_df.head())

MAKE Matrix dimensions: (167, 167)
MAKE Matrix head:
             0              1              2            3             4    \
0  SECTORNUMBER       1.000000       2.000000     3.000000      4.000000   
1             1  188013.411000       0.002401   319.428773   1193.368637   
2             2       0.002399  202423.242600    23.434574     87.550304   
3             3       5.911953       0.000085   814.098399   3041.427630   
4             4      22.086736       0.000316  3041.427630  11362.609280   

        5            6             7             8             9    ...  \
0  5.000000     6.000000  7.000000e+00  8.000000e+00  9.000000e+00  ...   
1  1.000372  1070.787249  5.998980e-08  1.200010e-08  2.399780e-08  ...   
2  0.000400  1024.200207  3.998040e-08  7.997510e-09  1.599340e-08  ...   
3  0.000021     0.000021  7.036260e-09  1.407500e-09  2.814720e-09  ...   
4  0.000079     0.000079  2.628710e-08  5.258360e-09  1.051570e-08  ...   

            157           158         

In [4]:
# Load Real Industry output table
indoutput_df = pd.read_csv('REAL_INDOUTPUT.csv', header=None)
print("REAl_INDOUTPUT TABLE dimensions:", indoutput_df.shape)
print("REAl_INDOUTPUT TABLE head:\n", indoutput_df.head())


REAl_INDOUTPUT TABLE dimensions: (168, 28)
REAl_INDOUTPUT TABLE head:
              0              1              2              3              4   \
0  SECTORNUMBER    1997.000000    1998.000000    1999.000000    2000.000000   
1             1  155926.530200  155647.537300  157832.432700  161056.844300   
2             2  153995.229500  156380.075600  161119.828200  161924.415200   
3             3    1964.220362    2218.117702    2702.485715    2525.813538   
4             4   19679.346140   23437.887430   27492.520320   22533.829460   

              5              6              7              8              9   \
0    2001.000000    2002.000000    2003.000000    2004.000000    2005.000000   
1  155511.944200  150412.580600  161253.983100  169225.998700  167645.502000   
2  163574.968600  166961.392200  166529.145500  169234.401900  173273.135900   
3    3234.807377    3701.606228    3215.960788    5768.562207    3279.278318   
4   22816.197830   24134.399340   24664.044790   23534

In [5]:
# Load Real commodity output table
comoutput_df = pd.read_csv('REAL_COMOUTPUT.csv', header=None)
print("REAl_COMOUTPUT TABLE dimensions:", comoutput_df.shape)
print("REAl_COMDOUTPUT TABLE head:\n", comoutput_df.head())

REAl_COMOUTPUT TABLE dimensions: (167, 28)
REAl_COMDOUTPUT TABLE head:
              0              1              2              3              4   \
0  SECTORNUMBER    1997.000000    1998.000000    1999.000000    2000.000000   
1             1  149784.248300  149176.706500  151419.967900  155998.551600   
2             2  149636.333400  151731.581100  156360.896600  158174.613200   
3             3    3506.492223    4118.951013    4739.099953    3946.896913   
4             4   20664.865400   24274.278350   27929.011790   23260.309240   

              5              6              7              8              9   \
0    2001.000000    2002.000000    2003.000000    2004.000000    2005.000000   
1  150878.355900  145792.113900  156370.399500  164237.581000  163390.680000   
2  159921.252200  163119.450500  162892.679000  165727.991900  170299.800800   
3    4047.134147    4290.299517    4345.844391    4580.999791    4618.309167   
4   23851.038900   25284.089170   25611.432640   2699

In [6]:
# Convert DataFrames to NumPy arrays
use_matrix = use_df.values
make_matrix = make_df.values
indoutput_matrix = indoutput_df.values
comoutput_matrix = comoutput_df.values


# take headers off
use_matrix = use_matrix[1:, 1:]
make_matrix = make_matrix[1:, 1:]
indoutput_matrix = indoutput_matrix[1:, 1:]
comoutput_matrix = comoutput_matrix[1:, 1:]


# LEONTIEF EQUATION
## (I-DB)g = De
## We are solving for production vector gcalc( total industry output)
gcalc = L*d

gcalc = (I - (V'$\hat{q}$' ^-1)(U'$\hat{g}$'^-1))^-1 * (V'$\hat{q}$'^-1)* e


In [7]:
# Extract V (make matrix: commodities by commodities, rows 0-165, columns 0-165)
V = make_matrix[0:166, 0:166]
print("\nV (Make Matrix):")
print("Shape:", V.shape)  # Should be (166, 166)
print("Values:\n", V)





V (Make Matrix):
Shape: (166, 166)
Values:
 [[188013.411 0.002400772 319.4287735 ... 3.01489e-08 5.99869e-08
  5.99896e-08]
 [0.002399244 202423.2426 23.43457448 ... 2.00928e-08 3.99785e-08
  3.99803e-08]
 [5.911952837 8.45046e-05 814.0983992 ... 3.53619e-09 7.03592e-09
  7.03623e-09]
 ...
 [2.98512e-08 1.99071e-08 3.50209e-09 ... 1553178.0 4.97409e-08
  4.97431e-08]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]]


In [8]:
# Extract U (intermediate portion: commodities by industries, rows 0-165, columns 0-165)
U = use_matrix[0:166, 0:166]
print("\nU (Intermediate Use Matrix):")
print("Shape:", U.shape)  # Should be (166, 166)
print("Values:\n", U)


U (Intermediate Use Matrix):
Shape: (166, 166)
Values:
 [[24060.87937 7719.985981 8.22684e-05 ... 0.000539498 0 0]
 [820.8561183 51235.61263 6.40794e-05 ... 0.000420219 0 0]
 [9.34055e-05 5.31791e-05 71.58719429 ... 1.31096e-05 0 0]
 ...
 [0.0 0.0 0.0 ... 0.0 0 0]
 [0.002194614 0.000717442 2.69697e-05 ... 0.000176862 0 0]
 [488.7812921 523.4383481 0.26018629 ... 8.53123e-05 0 0]]


In [9]:


# Extract the Total commodity output vector for 2017 (column 20 in zero-based indexing)
q = comoutput_matrix[0:166, 20]
print("\nq (Total commodity output vector for 2017)")
print("Shape:", q.shape)  # Should be (166, 1)
print("q_2017 (Commodity Output for 2017):", q)



q (Total commodity output vector for 2017)
Shape: (166,)
q_2017 (Commodity Output for 2017): [188237.4705 202952.428 4502.754671 16822.04814 9239.101769 29718.0964
 212664.0024 27800.70851 27315.39901 29359.96477 118269.9331 455761.4557
 80214.41181 80966.81977 1669683.071 53884.04469 78079.83289 38002.21535
 71980.31513 112782.3177 216867.9903 13836.02406 76083.35127 118589.3444
 178872.625 45803.99633 16549.01295 35951.89408 23986.14808 47155.95393
 76132.0262 105793.0473 68897.03204 529737.0775 416877.3184 207950.385
 117193.635 191326.7594 42127.22745 124976.0025 101975.0845 9244.964266
 34362.6975 45961.54988 28818.67436 121306.2623 117308.8055 66156.3891
 26121.57893 263255.0924 24090.63753 32673.62638 46189.69695 20348.54922
 35800.0271 3096.760328 94287.83488 147287.765 1927.031485 12899.60021
 23786.85125 35996.13851 47712.39802 277585.9323 43525.74488 256248.3518
 243888.6698 12654.40158 24875.17467 31236.64711 63964.35816 10062.65211
 83939.60765 60469.38252 2034923.866 319

In [10]:
# Extract the Total industry output vector for 2017 (column 20 in zero-based indexing)
g = indoutput_matrix[0:166, 20]
print("\ng (Total industry output vector for 2017)")
print("Shape:", g.shape)  # Should be (166, 1)
print("q_2017 (industry Output for 2017):", g)


g (Total industry output vector for 2017)
Shape: (166,)
q_2017 (industry Output for 2017): [191305.4837 204223.5163 3970.274133 14832.72963 8929.0 25650.0 253994.0
 36917.36246 29553.29016 35381.34738 106929.0 389397.1692 69553.03176
 15136.8404 1577966.0 54980.0 78985.0 37054.0 66005.0 123411.0 216259.0
 13837.0 69769.0 116183.0 176637.0 49704.0 15711.0 33015.0 24572.0 50868.0
 77403.41772 107895.5823 83928.0 538793.0 401823.0 255027.0 125800.0
 194080.8163 43682.18372 127320.0 88122.39537 22956.10299 35656.15997
 46252.20751 29900.13415 129021.6274 123796.6425 67526.80499 25933.92511
 272085.0 26410.0 32964.0 46808.0 33116.09347 43111.12168 3122.008812
 114393.3229 158692.4479 1868.005272 13478.0 22662.0 38420.0 49694.0
 279067.0 49215.0 268889.0 262744.0 12802.0 36006.0 24013.0 66089.86639
 10192.13361 95025.0 63824.0 2053877.0 373504.903 254330.7508 248738.3342
 971146.1746 236301.0 79569.0 54977.0 367154.0 78301.0 48072.0 141646.2426
 97060.0 123834.0 281987.8511 150723.526 65808

In [11]:
# Extract the final demand vector for 2017 (column 167 from use matrix)
e = use_matrix[0:166, 166]
print("\ne (final demand vector for 2017)")
print("Shape:", e.shape)  # Should be (166, 1)
print("e_2017 (final demand for 2017):", e)


e (final demand vector for 2017)
Shape: (166,)
e_2017 (final demand for 2017): [59538.53194 9070.468058 1488.731358 -1719.217081 -4237.713735 71.19945838
 -119297.0 3527.616955 7658.401404 -1300.018358 101777.0 177974.6846
 48711.13947 40309.1759 1375090.0 22164.80144 18601.66676 22330.74511
 47883.99603 55732.35268 117626.8456 2094.216063 62906.44329 72226.4833
 139011.4497 -379.0 5678.0 -4047.591501 -6287.615373 4922.206873
 12628.76023 8714.23977 2451.0 204900.0 13264.79535 101901.2786
 59759.92606 6491.023452 3028.976548 -5478.0 -21116.39358 -2366.413961
 -11552.56117 -13254.37337 236.742084 -7105.936481 5170.547727
 -672.5071303 374.8958845 155064.441 12395.2033 18646.0365 6897.319154
 -2381.957079 -7163.643347 -32.8757356 -10051.14829 96842.43081
 -36.8063607 -10287.08723 12979.27426 2271.930753 4727.88222 275649.616
 35471.70676 -45833.32276 141821.726 8481.163501 17673.3058 25517.80469
 33368.41151 9479.588488 33312.80082 37155.19918 1096002.22 298548.3396
 239732.1938 236667.

In [12]:

# Replace zeros in g and q with a small value to avoid division by zero, cast to float
g_safe = np.where(g == 0, 1e-10, g).astype(float)
q_safe = np.where(q == 0, 1e-10, q).astype(float)



Market share matrix = Make matrix * inverse of total commodity output vector(square matrix, with elements in main diagonal)
D =  V '$\hat{q}$'^-1



In [13]:


# Construct diagonal square matrice for q
q_hat = np.diag(q_safe)
# Calculate the inverse of q_hat safely
q_hat_inv = np.diag(1 / q_safe) 
# Market share matrix = Make matrix * q_hat_inv , @ for matrix multiplication
D = V.astype(float) @ q_hat_inv


Direct inputs coefficient matrix = Intermediates of USE matrix * inverse of total industry output vector(square matrix, with elements in main diagonal)
#
B =  U '$\hat{g}$'^-1

In [14]:

# Construct diagonal square matrix for g
g_hat = np.diag(g_safe)
# Calculate the inverse of g_hat safely
g_hat_inv = np.diag(1 / g_safe)
# Direct inputs coefficients matrix = U * g_hat_inv
B = U.astype(float) @ g_hat_inv



# Consumption Matrix = Direct inputs coefficient Matrix * Market Share Matrix
# C = DB


In [15]:

C = B @ D

# Leontief inverse matrix = (identity matrix - consumption matrix)^-1
L = (I-C)^-1

In [16]:
# Create the identity matrix of size 166x166
I = np.eye(166)
# L = (I-C)^-1
L = np.linalg.inv(I - C)



# Total comodity output = Leontief inverse matrix * final demand
qcalc = L * e

In [17]:

q_calc = L @ e.astype(float)



# Total industry output = market share matrix * total commodity output
gcalc = D * qcalc

In [18]:


g_calc = D @ q_calc


In [19]:


# Verification
print("g (original):", g)
print("g_calc:", g_calc)

#check for negative values in g_calc
if np.any(g_calc < 0):
    print("The economy is not productive because g_calc contains negative values.")
else:
    print("The economy is productive because g_calc does not contain negative values.")


g (original): [191305.4837 204223.5163 3970.274133 14832.72963 8929.0 25650.0 253994.0
 36917.36246 29553.29016 35381.34738 106929.0 389397.1692 69553.03176
 15136.8404 1577966.0 54980.0 78985.0 37054.0 66005.0 123411.0 216259.0
 13837.0 69769.0 116183.0 176637.0 49704.0 15711.0 33015.0 24572.0 50868.0
 77403.41772 107895.5823 83928.0 538793.0 401823.0 255027.0 125800.0
 194080.8163 43682.18372 127320.0 88122.39537 22956.10299 35656.15997
 46252.20751 29900.13415 129021.6274 123796.6425 67526.80499 25933.92511
 272085.0 26410.0 32964.0 46808.0 33116.09347 43111.12168 3122.008812
 114393.3229 158692.4479 1868.005272 13478.0 22662.0 38420.0 49694.0
 279067.0 49215.0 268889.0 262744.0 12802.0 36006.0 24013.0 66089.86639
 10192.13361 95025.0 63824.0 2053877.0 373504.903 254330.7508 248738.3342
 971146.1746 236301.0 79569.0 54977.0 367154.0 78301.0 48072.0 141646.2426
 97060.0 123834.0 281987.8511 150723.526 658082.9167 176234.0197
 495825.8644 1057917.0 549317.0 157361.0 680230.0 362909.0 

In [20]:

print("q (original):", q)
print("q_calc:", q_calc)

q (original): [188237.4705 202952.428 4502.754671 16822.04814 9239.101769 29718.0964
 212664.0024 27800.70851 27315.39901 29359.96477 118269.9331 455761.4557
 80214.41181 80966.81977 1669683.071 53884.04469 78079.83289 38002.21535
 71980.31513 112782.3177 216867.9903 13836.02406 76083.35127 118589.3444
 178872.625 45803.99633 16549.01295 35951.89408 23986.14808 47155.95393
 76132.0262 105793.0473 68897.03204 529737.0775 416877.3184 207950.385
 117193.635 191326.7594 42127.22745 124976.0025 101975.0845 9244.964266
 34362.6975 45961.54988 28818.67436 121306.2623 117308.8055 66156.3891
 26121.57893 263255.0924 24090.63753 32673.62638 46189.69695 20348.54922
 35800.0271 3096.760328 94287.83488 147287.765 1927.031485 12899.60021
 23786.85125 35996.13851 47712.39802 277585.9323 43525.74488 256248.3518
 243888.6698 12654.40158 24875.17467 31236.64711 63964.35816 10062.65211
 83939.60765 60469.38252 2034923.866 319690.9049 242029.7707 242617.9438
 964524.3889 231561.9891 78668.02406 53009.9993

# Using the Leontief model to predict inter-industry behavior in 2033


In [ ]:
#!pip install plotly
#!pip install ipywidgets
#!pip install ipython
#!pip install --upgrade nbformat

In [21]:

# Import additional libraries for visualization
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from ipywidgets import widgets, Layout
from IPython.display import display, clear_output



In [22]:


# Load 2033 data 
use_2033_df = pd.read_csv('PROJECTED_USE_2033.csv', header=None)
make_2033_df = pd.read_csv('PROJECTED_MAKE_2033.csv', header=None)
final_demand_2033_df = pd.read_csv('PROJECTED_FD_2033.csv', header=None)
output_df = pd.read_csv('PROJECTED_OUTPUT_2033.csv', header=None)
sector_plan_df = pd.read_csv('166_sectors.csv', header=None)



In [23]:


# Convert to arrays and remove headers
U_2033 = use_2033_df.values[1:167, 1:167].astype(float)  # 166 sectors
V_2033 = make_2033_df.values[1:, 1:167].astype(float)  # 166 sectors
e_2033 = use_2033_df.values[1:167, 167].astype(float)  # Last column as e_2033
g_2033 = output_df.values[1:167, 1].astype(float)  
q_2033 = output_df.values[1:167, 2].astype(float)  



In [24]:
# print shapes
print("U_2033 shape:", U_2033.shape)
print("V_2033 shape:", V_2033.shape)
print("e_2033 shape:", e_2033.shape)
print("g_2023 shape:", g_2033.shape)
print("q_2023 shape:", q_2033.shape)




U_2033 shape: (166, 166)
V_2033 shape: (166, 166)
e_2033 shape: (166,)
g_2023 shape: (166,)
q_2023 shape: (166,)


In [25]:
# print
print("U\n",U_2033)
print("V\n",V_2033)



U
 [[1.5094141e+04 6.9457840e+03 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [6.8497200e+02 6.1317685e+04 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 1.4054600e+02 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.0000000e-03 1.0000000e-03 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.4483800e+02 2.2245400e+02 9.1000000e-02 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]]
V
 [[1.87887472e+05 2.00000000e-03 5.27582000e+02 ... 1.20000000e-02
  0.00000000e+00 0.00000000e+00]
 [3.00000000e-03 2.53445827e+05 5.48550000e+01 ... 1.10000000e-02
  0.00000000e+00 0.00000000e+00]
 [4.55700000e+00 0.00000000e+00 1.08048500e+03 ... 1.00000000e-03
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.18624852e+06
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+

In [26]:
# print
print("e\n",e_2033)



e
 [ 8.84507030e+04  2.71652710e+04  1.72851900e+03 -1.62319200e+03
 -1.94879900e+03  1.94275000e+02  8.78644220e+04  5.21402400e+03
  5.62063600e+03 -2.01441300e+03  1.20639880e+05  2.22755453e+05
  4.96465610e+04  3.74425730e+04  1.58655962e+06  5.40791140e+04
  1.87464250e+04  3.12499850e+04  6.90349880e+04  8.29783520e+04
  1.56551311e+05  1.58735800e+03  7.69220230e+04  1.06082286e+05
  1.72240735e+05  9.28279000e+02  3.10152680e+04 -6.69472100e+03
 -6.43301400e+03  1.27344400e+03  7.78761900e+03  3.48780900e+03
  2.30539700e+03  2.49731709e+05 -2.36620810e+04  1.65512632e+05
  1.11931606e+05 -2.06872440e+04  3.19069100e+03 -1.82281200e+04
 -2.24176210e+04 -4.31979700e+03 -1.40460060e+04 -2.05400970e+04
 -4.89196000e+02 -3.51898880e+04 -5.02558000e+02 -6.26012500e+03
  5.40510000e+02  1.41498274e+05  7.82545100e+03  1.18967500e+04
 -6.02664000e+02  1.10359160e+04 -5.19097160e+04  8.28339000e+03
 -6.87724670e+04  1.13077302e+05 -4.51600000e+01 -2.29224140e+04
  2.28313060e+04 -2.49

In [27]:
# print
print("g\n",g_2033)



g
 [1.92696190e+05 2.56941010e+05 5.03322100e+03 2.36433120e+04
 8.52109800e+03 2.77197860e+04 5.21382958e+05 2.56048010e+04
 3.24424390e+04 4.30359930e+04 8.83633480e+04 4.91704108e+05
 8.38499710e+04 1.53845700e+04 1.84821439e+06 6.03368120e+04
 9.13856740e+04 3.57835230e+04 7.01093680e+04 1.51407134e+05
 2.63563365e+05 1.39311880e+04 6.88181090e+04 1.33001842e+05
 1.94365404e+05 3.91098730e+04 1.85928670e+04 4.83295590e+04
 2.16921630e+04 6.81285500e+04 5.55434630e+04 1.03942752e+05
 6.05697480e+04 5.36413891e+05 3.97148306e+05 4.08708824e+05
 1.38392626e+05 1.86040369e+05 4.43765650e+04 1.21393370e+05
 1.09019926e+05 2.68100760e+04 4.33062230e+04 6.38705020e+04
 2.89521700e+04 1.11398503e+05 1.12067232e+05 6.63592920e+04
 2.54351820e+04 2.55117498e+05 2.79100090e+04 3.21782600e+04
 3.93208710e+04 4.53604150e+04 6.92967510e+04 5.97907200e+03
 1.91206639e+05 1.76813819e+05 1.44208400e+03 1.19022090e+04
 2.73331350e+04 4.20523420e+04 5.28193610e+04 5.23951468e+05
 7.63291650e+04 2.200

In [ ]:
# print
print("q\n",q_2033)


In [28]:



# Sector mapping (from sector plan document)
sector_plan = sector_plan_df.values[0:166, 0:2]  # Extract the first two columns (IDs and names)
sector_map = dict(zip(sector_plan[:, 0], sector_plan[:, 1]))  # Map IDs to names

# Print the sector map to verify
print("Sector Map:")
for sector_id, sector_name in sector_map.items():
    print(f"{sector_id}: {sector_name}")

Sector Map:
1: Crop production
2: Animal production and aquaculture
3: Forestry
4: Logging
5: Fishing, hunting and trapping
6: Support activities for agriculture and forestry
7: Oil and gas extraction
8: Coal mining
9: Metal ore mining
10: Nonmetallic mineral mining and quarrying
11: Support activities for mining
12: Electric power generation, transmission and distribution
13: Natural gas distribution
14: Water, sewage and other systems
15: Construction
16: Animal food manufacturing
17: Grain and oilseed milling
18: Sugar and confectionery product manufacturing
19: Fruit and vegetable preserving and specialty food manufacturing
20: Dairy product manufacturing
21: Animal slaughtering and processing
22: Seafood product preparation and packaging
23: Bakeries and tortilla manufacturing
24: Other food manufacturing
25: Beverage and tobacco product manufacturing
26: Textile mills and textile product mills
27: Apparel, leather and allied product manufacturing
28: Sawmills and wood preservatio

# Example Sector: Computing infrastructure providers, data processing, web hosting, and related services

In [31]:



# Compute 2033 production (similar to 2017)
g_safe_2033 = np.where(g_2033 == 0, 1e-10, g_2033)
q_safe_2033 = np.where(q_2033 == 0, 1e-10, q_2033)
D_2033 = V_2033 @ np.diag(1 / q_safe_2033)
B_2033 = U_2033 @ np.diag(1 / g_safe_2033)
C_2033 = B_2033 @ D_2033
L_2033 = np.linalg.inv(np.eye(166) - C_2033)
q_calc_2033 = L_2033 @ e_2033
g_calc_2033 = D_2033 @ q_calc_2033

# Interactive visualization function taken and adapted from https://plotly.com/python/
def update_plot(sector_name):
    clear_output(wait=True)
    sector_num = [k for k, v in sector_map.items() if v.lower() == sector_name.lower()]
    if not sector_num:
        print("Sector not found. Please try again.")
        return
    sector_idx = sector_num[0] - 1  # Adjust for 0-based indexing
    
    # Data for the selected sector
    g_2017_val = g[sector_idx]
    g_2033_val = g_calc_2033[sector_idx]
    q_2017_val = q[sector_idx]
    q_2033_val = q_calc_2033[sector_idx]
    intermediate_use = U_2033[sector_idx, :].sum()
    final_demand = e_2033[sector_idx]
    
    # Create subplots
    fig = make_subplots(rows=1, cols=3, subplot_titles=("Production Comparison", "Demand Breakdown", "Output Trend"),
                        specs=[[{"type": "bar"}, {"type": "pie"}, {"type": "scatter"}]])
    
    # Bar chart: Production comparison
    fig.add_trace(go.Bar(x=["2017 Industry", "2033 Industry", "2017 Commodity", "2033 Commodity"],
                         y=[g_2017_val, g_2033_val, q_2017_val, q_2033_val], name="Production"),
                  row=1, col=1)
    
    # Pie chart: Demand breakdown
    fig.add_trace(go.Pie(labels=["Intermediate Use", "Final Demand"], values=[intermediate_use, final_demand],
                         name="Demand Breakdown"), row=1, col=2)
    
    # Line chart: Trend (using available years; extend to 2033 with prediction)
    years = [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2033]
    g_trend = list(indoutput_df.values[sector_idx + 1, 20:]) + [g_2033_val]  # 2017-2023 + 2033
    fig.add_trace(go.Scatter(x=years, y=g_trend, mode="lines+markers", name="Industry Output Trend"),
                  row=1, col=3)
    
    # Update layout
    fig.update_layout(title_text=f"Production Analysis for {sector_name} (Sector {sector_num[0]})",
                      height=400, width=1200, showlegend=True)
    fig.show()

# UPDATE SECTOR NAME Computing infrastructure providers, data processing, web hosting, and related services
sector_input = widgets.Text(value="Computing infrastructure providers, data processing, web hosting, and related services", description="Sector Name:", layout=Layout(width="50%"))
update_button = widgets.Button(description="Update Plot", button_style="success")

# Define button click event
def on_button_clicked(b):
    update_plot(sector_input.value)

update_button.on_click(on_button_clicked)

# Display widgets and initial plot
display(widgets.HBox([sector_input, update_button]))
update_plot(sector_input.value)